server:
  port: 0

spring:
  application:
    name: MS-RANKINGS
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: rankingdb
springdoc:
  api-docs:
    path: /aulamatriz-doc
  show-actuator: true
  packages-to-scan: com.ms.ranking.service.msranking.controller

#Eureka
eureka:
  instance:
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka